server:
  port: ${PORT:5000}

spring:
  application:
    name: api-gateway-application
rest:
  publications:
    url: https://post-system-196.herokuapp.com/v1/
  subscription:
    url: http://178.250.157.184:6001/api/v1/
